[build]
  base = "client"
  publish = ".next"
  command = "npm install --force && npm run build"

[[plugins]]
package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/api/*"
  to = "https://embala-fest-server.onrender.com/api/:splat"
  status = 200
  force = true