[build]
  publish = ".next"
  command = "npm install --force && npm run build"

[[plugins]]
package = "@netlify/plugin-nextjs"


[[redirects]]
  from = "/api/*"
  to = "https://embala-fest-api.onrender.com/api/:splat"
  status = 200
  force = true

  [redirects.headers]
    Access-Control-Allow-Origin = "https://embalafest.netlify.app"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept, Authorization"
    # Confirmar que não estamos cacheando as respostas
    Cache-Control = "no-cache"


[[redirects]]
  from = "/api/*"
  to = "https://embala-fest-api.onrender.com/api/:splat"
  status = 204
  force = true
  methods = ["OPTIONS"]
  
  [redirects.headers]
    Access-Control-Allow-Origin = "https://embalafest.netlify.app"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept, Authorization"
    Cache-Control = "no-cache"

# Rotas do Next.js
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/next"
  status = 200


[build.processing.js]
  bundle = true
  minify = true

[functions]

  node_bundler = "esbuild"
  external_node_modules = ["@netlify/functions"]
  included_files = ["!node_modules/.pnpm/**"]